### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by man4toman**

### CODE REVIEW

**Comment by JulieKuehl** [comment]
We'd like to remove all the links to the `make.wordpress.org` site for lesson plans. Could you please use `https://github.com/wptrainingteam/child-themes` instead?

The other changes look good!

**Comment by man4toman** [comment]
@JulieKuehl I create new PR, but we don't have any repo for: **Teacher Resources page**

**Comment by man4toman** [comment]
Hi @JulieKuehl 
Would you please check the update?

**Comment by JulieKuehl** [comment]
Thank you for your contribution! Your pull request has been merged.

**Pull request merged**
